theme: jekyll-theme-minimal
title: F(x)Lab
description: Global Digital Innovation Agency
logo: https://raw.githubusercontent.com/ZihaoLu/FXLAB/4727348196b1b61703da402dc656236b3d0def3e/F(x)Lab_Logo.jpg
show_downloads: true
